#!/bin/bash
#This script generates the automatic labeler for the 3b1b/captions repository

languages=("german" "hebrew" "french" "spanish" "turkish" "hindi" "hungarian" "arabic" "bengali" "chinese" "croation" "indonesian" "italian" "japanese" "korean" "lithuanian" "marathi" "persian" "polish" "portuguese" "romanian" "russian" "serbian" "slovak" "thai" "ukranian" "vietnamese")
labeler_file=".github/labeler.yml"

echo "# This file was automatically generated by the labeler.sh script. Do not edit manually." > $labeler_file
echo "" >> $labeler_file

for language in "${languages[@]}"
do
    # Set the label name, with the first letter capitalized 
    label_name=$(echo "$language" | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}')

    {
        echo "$label_name:"
        echo "- changed-files:"
        echo "  - any-glob-to-any-file: '**/$language/*'"
        echo ""
    } >> $labeler_file
done




