name: Update app data
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./app

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Install packages
        run: bun install

      - name: Run update
        run: bun run update

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data"
